packages:
  onju_voice_assistant: !include voice_assistant.yaml

external_components:
  - source:
      type: git
      url: https://github.com/tetele/home-assistant-voice-pe
      ref: fix-mww-guarding
    components:
      - voice_assistant
    # refresh: 0s

voice_assistant:
  microphone: onju_microphone
  media_player: onju_out
  use_wake_word: false
  noise_suppression_level: 0
  auto_gain: 0 dbfs
  volume_multiplier: 1
  on_end:
    then:
      - lambda: id(voice_assistant_phase) = ${voice_assist_idle_phase_id};
      - script.execute: control_led
