substitutions:
  name: "onju-voice"
  friendly_name: "Onju Voice Satellite"
  project_version: "2.0.0-b0"
  device_description: "Onju Voice Satellite with ESPHome software and microWakeWord"

packages:
  onju_base: !include onju-modules/base.yaml
  onju_ble_improv: !include onju-modules/ble_improv.yaml
  onju_leds: !include onju-modules/leds.yaml
  onju_controls: !include onju-modules/controls.yaml
  # audio_gnumpi: !include onju-modules/audio-gnumpi.yaml
  # onju_va_mww: !include onju-modules/micro_wake_word.yaml
